name: Test SSH connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection ${{ vars.SSH_HOST }} ${{ vars.SSH_PORT }} ${{ vars.SSH_USERNAME }}
        uses: appleboy/ssh-action@v1.2.2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ vars.SSH_HOST }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USERNAME }}
          script: |
            echo "✅ SSH connection successful!"
            whoami
            hostname
            uptime
